export type Params = {
  area: number;
  population: number;
  penetration: number;
  active: number;
  growth: number;
  frequency: number;
  bandwidth: number;
  height: number;
  mobileHeight: number;
  gain: number;
  power: number;
  cable: number;
  sensitivity: number;
  fade: number;
  other: number;
  receiveGain: number;
  distance: number;
  radius: number;
  overlap: number;
  efficiency: number;
  demand: number;
  calls: number;
  duration: number;
  reuse: number;
  tilt: number;
  horizontal: number;
  vertical: number;
};
export type BTS = {
  id: string;
  lat: number;
  lng: number;
  height: number;
  power: number;
  frequency: number;
  gain: number;
  sectors: number;
  azimuth: number;
  tilt: number;
  radius: number;
  enabled: boolean;
};
export type FieldPoint = {
  id: string;
  lat: number;
  lng: number;
  rsrp: number;
  rsrq: number;
  sinr: number;
  download: number;
  upload: number;
  latency: number;
  note: string;
  real: boolean;
};
